### ISSUE TITLE
Logging Key Error

### ISSUE THREAD

**Issue by LRahlff** [Mission-DMX/Project-Editor#149]
Beim Laden der Showfile: [test2.show.txt](https://github.com/Mission-DMX/Project-Editor/files/15098636/test2.show.txt) kommt es zu der Fehlermeldung: KeyError
Traceback (most recent call last):
  File "/home/scarfface/Dokumente/COAL/Lichtpult/Mission-DMX/Project-Editor/src/view/logging_mode/logging_widget.py", line 84, in new_log_message
    self._levels[level].isChecked(), self._loging_level_changed)
    ~~~~~~~~~~~~^^^^^^^
KeyError: 'WARNING'
Traceback (most recent call last):
  File "/home/scarfface/Dokumente/COAL/Lichtpult/Mission-DMX/Project-Editor/src/view/logging_mode/logging_widget.py", line 84, in new_log_message
    self._levels[level].isChecked(), self._loging_level_changed)
    ~~~~~~~~~~~~^^^^^^^
KeyError: 'CRITICAL'
[Here](https://github.com/Mission-DMX/Project-Editor/blob/main/src/view/logging_mode/logging_widget.py#L28) is WARN defined but not WARNING and CRITICAL.
Could you take a look to that problem?

**Comment by Doralitze** [comment]
I think @maxkaussow already fixed that one in either his debug improvement branch or with pull request #146.
